development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: projeto_development
  username: postgres
  password: system

test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: projeto_test
  username: postgres
  password: system




  # MySQL.  Versions 5.0+ are recommended.

#
  #default: &default
    #adapter: mysql2
    #encoding: utf8
    #pool: 5
    #username: root
    #password: system
    #socket: /var/run/mysqld/mysqld.sock

#development:
  #<<: *default
  #database: projeto_development

#test:
  #<<: *default
  #database: projeto_test


#
#production:
  #<<: *default
  #database: projeto_production
  #username: projeto
  #password: <%= ENV['PROJETO_DATABASE_PASSWORD'] %>
